version: '3'

services:
  celonis-demo:
    build: .
    ports:
      - 8080:8080
    container_name: backend
    depends_on:
      - redis-demo
    links:
      - redis-demo
  redis-demo:
    image: redis
    build: ./redisConf
    ports:
      - 6379:6379
    container_name: redis-cache
#  h2-database:
#    image: